apiVersion: v1
kind: Service
metadata:
  name: frontendonly-service
  labels:
    app: sdvdemo
spec:
  ports:
  - protocol: "TCP"
   # Port accessible inside cluster
    port: 8888
    # Port accessible outside cluster nodePort
    nodePort: 30002
     # Port to forward to inside the pod targetpod
    #targetPort: 8888
  selector:
    app: sdvdemo
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendonly-deployment
  labels:
    app: sdvdemo
spec:
  selector:
    matchLabels:
      app: sdvdemo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sdvdemo
        tier: frontend
    spec:
      containers:
      - image: markusfelsner/sdvdemo-frontendonly:1.0 #tutum/hello-world
        name: sdvdemo
        #ports:
          #- containerPort: 8888