apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: sdvdemo
spec:
  ports:
    - port: 8888
  selector:
    app: sdvdemo
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: sdvdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdvdemo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sdvdemo
        tier: frontend
    spec:
      containers:
      - image: markusfelsner/sdvdemo-frontend:1.0
        name: sdvdemo
        ports:
          - containerPort: 8888